# Project information
site_name: "M-Power Sitedocs"
site_description: "Official M-Power Site"
site_author: "Jeffrey T. Lucas <Jeffrey.Lucas@McKesson.com>"
site_url: "http://localhost:8080/sitedocs/"

# Copyright
copyright: "&copy; 2024, baseonballs email:lucasjt@gmail.com>"

# Repository
repo_name: "GitHub"
#repo_url: "https://github.com/CoverMyMeds-Pharmacy/peng-cloud-delivery-sitedocs.git"
#edit_uri: "https://github.com/CoverMyMeds-Pharmacy/peng-cloud-delivery-sitedocs/site-docs"

# Configuration

docs_dir: "site-docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "red"
    accent: "break"
  features:
    - tabs
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - footnotes
  # - mdx_math:
  #     enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"
# Navitgation
nav:
  - "M-Power Mathmatics Sitedocs": "index.md"
  - "Language of Math":
    - "Symbols and Notations":
      - "Mathematic Notation & Syntax": "./mathematics/a1/appendix/lang/semantics.md"
      - "Arithmetic Operators": "./mathematics/a1/appendix/lang/notation_arithmetic_operators.md"
      - "Logic Notation": "./mathematics/a1/appendix/lang/notation_logic.md"
      - "Set Notation": "./mathematics/a1/appendix/lang/notation_sets.md"
      - "Sigma Notation": "./mathematics/a1/appendix/lang/notation_sigma.md"
    - "Algebraic Equations":
      - "Terms and Expressions": "./mathematics/a1/appendix/lang/structure_expressions_and_terms.md"
      - "Structure of Equalities": "./mathematics/a1/appendix/lang/structure_equations.md"
      - "Structure of Inequalities": "./mathematics/a1/appendix/lang/structure_inqualities.md"
      - "Structure of Polynomials": "./mathematics/a1/appendix/lang/structure_polynomials.md"
  - "Math Puzzles and Excursions":
    - "Elementary Puzzles": "./mathematics/puzzles/index.md"
    - "Did You Know?": "./mathematics/puzzles/did_you_know.md"
  - "Elementary Mathamatics":
    - "Number Sets" : "./mathematics/a1/appendix/sets/set_numbers.md"
    - "Base 10": "./mathematics/em/base10/index.md"
  - "Algebra 1":
    - "Equation Forms & Structures":
      - "Intro": "page-404.md"
    - "Linear Equations":
      - "Functions": "page-404.md"
      - "Graphs": "page-404.md"
    - "Quadratic Equations":
      - "Overview": "page-404.md"
    - "Appendix - Resources":
      - "Definitions":
        - "Rational Exponents": "./mathematics/a1/defs/exp_rational.md"
      - "Laws & Properties":
        - "Fundamental Theorem of Arithmetic": "./mathematics/a1/appendix/fundamental_theorem_arithmetic.md"
        - "Fundamental Theorem of Algebra": "./mathematics/a1/appendix/fundamental_theorem_algebra.md"
        - "Laws of Equalities & Inequalities": "./mathematics/a1/appendix/laws_eq_ineq.md"
        - "Laws of Exponents": "./mathematics/a1/appendix/law_of_exponents.md"
        - "Peano Axioms": "./mathematics/a1/appendix/peano_axioms.md"
      - "Theorems":
        - "General": "./mathematics/a1/appendix/theorems/index.md"
        - "Quadratic Thorems": "./mathematics/a1/appendix/theorems/quadraics.md"
        - "Pythagorean Theorem": "./mathematics/a1/appendix/pythagoren_theorem.md"
      - "Challenging Problems":
        - "Solve for x":
          - "Problem 1 - Radical": "./mathematics/a1/psets-a1/q1-solve-for-x.md"
          - "Problem 2 - Simultaneous Eq.": "./mathematics/a1/psets-a1/q2-solve-for-x.md"
          - "Problem 3 - Rational Powers": "./mathematics/a1/psets-a1/q3-solve-for-x.md"
          - "Problem 4 - Powers": "./mathematics/a1/psets-a1/q4-solve-for-x.md"
          - "Problem 5 - Linear Eq.": "./mathematics/a1/psets-a1/q5-solve-for-x.md"
      - "Cheatsheets":
        - "Algebraic Identities":  "./mathematics/a1/appendix/algebraic_identities.md"
  - "Algebra 2":
    - "Trignometic Functions":
      - "Empty": "page-404.md"
  - "Modular Arithematic":
    - "Remainders":
      - "Empty": "page-404.md"
  - "Geometry":
    - "Trignometic Functions":
      - "Empty": "page-404.md"
  - "Number Theory":
    - "Factors & Multiples": "page-404.md"
    - "Primality": "page-404.md"
    - "Divisibility": "page-404.md"