# Project information
site_name: "M-Power Sitedocs"
site_description: "Official M-Power Site"
site_author: "Jeffrey T. Lucas <Jeffrey.Lucas@McKesson.com>"
site_url: "http://localhost:8080/sitedocs/"

# Copyright
copyright: "&copy; 2024, baseonballs email:lucasjt@gmail.com>"

# Repository
repo_name: "GitHub"
#repo_url: "https://github.com/CoverMyMeds-Pharmacy/peng-cloud-delivery-sitedocs.git"
#edit_uri: "https://github.com/CoverMyMeds-Pharmacy/peng-cloud-delivery-sitedocs/site-docs"

# Configuration

docs_dir: "site-docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "red"
    accent: "break"
  features:
    - tabs
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - footnotes
  # - mdx_math:
  #     enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"
