# Project information
site_name: "M-Power Sitedocs"
site_description: "Official M-Power Site"
site_author: "Jeffrey T. Lucas <Jeffrey.Lucas@McKesson.com>"
site_url: "http://localhost:8080/sitedocs/"

# Copyright
copyright: "&copy; 2024, baseonballs email:lucasjt@gmail.com>"

# Repository
repo_name: "GitHub"
#repo_url: "https://github.com/CoverMyMeds-Pharmacy/peng-cloud-delivery-sitedocs.git"
#edit_uri: "https://github.com/CoverMyMeds-Pharmacy/peng-cloud-delivery-sitedocs/site-docs"

# Configuration

docs_dir: "site-docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "red"
    accent: "break"
  features:
    - tabs
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - footnotes
  # - mdx_math:
  #     enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/peaceiris"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/piris314en"
# Navitgation
nav:
  - "M-Power Mathmatics Sitedocs": "index.md"
  - "Art of Problem Solving":
    - "Critical Thinking": "mathematics/aops/critical_thinking.md"
    - "Critical Framework": "mathematics/aops/critical_thinking_framework.md"
    - "Mental Excercise":
      - "Variable Assignment": "mathematics/critical-thinking/mental-excercise/x_equal_6.md"
      - "Number Assignment": "mathematics/critical-thinking/mental-excercise/6_equal_x.md"
      - "Infinity" : "mathematics/critical-thinking/mental-excercise/infinity/infinity.md"
    - "Tools & Resources" : "resources/index.md"
  - "Language of Math":
    - "Symbols and Notations":
      - "Mathematic Notation & Syntax": "./mathematics/a1/appendix/lang/semantics.md"
      - "Arithmetic Operators": "./mathematics/a1/appendix/lang/notation_arithmetic_operators.md"
      - "Logic Notation": "./mathematics/a1/appendix/lang/notation_logic.md"
      - "Set Notation": "./mathematics/a1/appendix/lang/notation_sets.md"
      - "Sigma Notation": "./mathematics/a1/appendix/lang/notation_sigma.md"
      - "Quantifiers":
        - "Logic Quantifiers": "./mathematics/a1/appendix/lang/notation_logic_quantifiers.md"
        - "Set Quantifiers": "./mathematics/a1/appendix/lang/notation_set_quantifiers.md"
        - "What's the Difference": "./mathematics/a1/appendix/lang/notation_diff_quantifiers.md"
    - "Algebraic Equations":
      - "Terms and Expressions": "./mathematics/a1/appendix/lang/structure_expressions_and_terms.md"
      - "Structure of Equalities": "./mathematics/a1/appendix/lang/structure_equations.md"
      - "Structure of Inequalities": "./mathematics/a1/appendix/lang/structure_inqualities.md"
      - "Structure of Polynomials": "./mathematics/a1/appendix/lang/structure_polynomials.md"
  - "Math Puzzles and Excursions":
    - "I ❤️ Puzzles":
      - "Math Competition":
        - "AMC-8": 
          - "Problem Set 1": "math-comp/amc8/amc8.pset.01.md"
          - "Problem Set 2": "math-comp/amc8/amc8.pset.02.md"
        - "AMC 10":
          - "Problem Set 1": "math-comp/amc10/amc10.pset.01.md"
        - "AMC 12":
          - "Problem Set 1": "math-comp/amc12/amc12.pset.01.md"
        - "AIME":
            - "Problem Set 1": "math-comp/aime/aime.pset.01.md"
        - "Olympiad":
            - "Problem Set 1": "math-comp/olympiad/olympiad.pset.01.md"
      - "Puzzle 1 - What is my number?": "./mathematics/elem/puzzles/level-a/puzzle-01.md"
      - "Puzzle 2 - Magic Square, 3x3": "./mathematics/elem/puzzles/level-a/magic-squares/ms-3x3.md"
      - "Puzzle 3 - Magic Square, 4x4": "./mathematics/elem/puzzles/level-a/magic-squares/ms-4x4.md"
      - "Puzzle 4 - Frog and the Stairs": "mathematics/elem/puzzles/level-a/frog-and-stairs/frog-and-the-stairs.md"
    - "Did You Know?": "./mathematics/puzzles/did_you_know.md"
    - "Patterns in Numbers": 
      - "Patterns in Nature": "mathematics/patterns/index.md"
      - "Hidden Patterns": "mathematics/patterns/hidden_patterns.md"
    - "Number Shapes": "mathematics/patterns/shapes/numbers.md"
  - "Elementary Mathamatics":
    - "Number Sets" : 
      - "Classification of Numbers": "./mathematics/elem/number-sets/set_numbers.md"
      - "Natural Numbers": "./mathematics/elem/number-sets/natural_numbers.md"
      - "Integers": "./mathematics/elem/number-sets/integers.md"
    - "Number System":
      - "Decimal - Base 10": "./mathematics/elem/number-system/decimal.md"
      - "Binary - Base 2":
        - "Introduction": "./mathematics/elem/number-system/binary.md"
        - "Exercises": "mathematics/elem/number-system/exercise/b10_to_b2-01.md"
      - "Hexdecimal - Base 16": "./mathematics/elem/number-system/hexidecimal.md"
  - "Algebra 1":
    - "Forms & Structures of Equations":
      - "Introduction": "mathematics/a1/eqs/forms/class-of-equations.md"
    - "Linear Equations":
      - "Introduction": "mathematics/a1/eqs/linear/intro.md"
      - "Semantic Structures":
        - "Introspection of Linear Forms": "mathematics/a1/eqs/linear/structures/semantics.md"
        - "Forms of Linear Eq.": "mathematics/a1/eqs/linear/index.md"
        - "Howto Deconstruct": "mathematics/a1/eqs/linear/deconstruction.md"
      - "Functions": "./mathematics/a1/eqs/linear/functions.md"
      - "Graphs": "./mathematics/a1/eqs/graphs.md"
    - "Quadratic Equations":
      - "Form & Structure": "./mathematics/a1/eqs/quadratics/index.md"
    - "Appendix - Resources":
      - "Definitions":
        - "Rational Exponents": "./mathematics/a1/defs/exp_rational.md"
      - "Laws & Properties":
        - "Fundamental Theorem of Arithmetic": "./mathematics/a1/appendix/fundamental_theorem_arithmetic.md"
        - "Fundamental Theorem of Algebra": "./mathematics/a1/appendix/fundamental_theorem_algebra.md"
        - "Laws of Equalities & Inequalities": "./mathematics/a1/appendix/laws_eq_ineq.md"
        - "Laws of Exponents": "./mathematics/a1/appendix/law_of_exponents.md"
        - "Peano Axioms": "./mathematics/a1/appendix/peano_axioms.md"
      - "Theorems":
        - "General": "./mathematics/a1/appendix/theorems/index.md"
        - "Quadratic Thorems": "./mathematics/a1/appendix/theorems/quadraics.md"
        - "Pythagorean Theorem": "./mathematics/a1/appendix/pythagoren_theorem.md"
      - "Challenging Problems":
        - "Solve for x":
          - "Problem 1 - Radical": "./mathematics/a1/psets-a1/q1-solve-for-x.md"
          - "Problem 2 - Simultaneous Eq.": "./mathematics/a1/psets-a1/q2-solve-for-x.md"
          - "Problem 3 - Rational Powers": "./mathematics/a1/psets-a1/q3-solve-for-x.md"
          - "Problem 4 - Powers": "./mathematics/a1/psets-a1/q4-solve-for-x.md"
          - "Problem 5 - Linear Eq.": "./mathematics/a1/psets-a1/q5-solve-for-x.md"
      - "Cheatsheets":
        - "Algebraic Identities":  "./mathematics/a1/appendix/algebraic_identities.md"
  - "Algebra 2":
    - "Trignometic Functions":
      - "Identities": "./mathematics/a2/trig.md"
  - "Geometry":
    - "Circle":
      - "Form & Structures": "./mathematics/geometry/form-structures.md"
      - "Circle Math": "./mathematics/geometry/circle-math.md"
    - "Shapes":
      - "Triangles": "./mathematics/geometry/triangle_overview.md"
  - "Modular Arithmetic":
    - "Clock Math": "./mathematics/mod-arith/clock-math.md"
    - "Modulo": "./mathematics/mod-arith/modulo.md"
    - "Modulus": "./mathematics/mod-arith/modulus.md"
    - "Remainder System": "./mathematics/mod-arith/remainder-system.md"
    - "Remainder Class": "./mathematics/mod-arith/remainder-class.md"
  - "Number Theory":
    - "Factors & Multiples": "./mathematics/nt/factors.md"
    - "Primality": "./mathematics/nt/primality.md"
    - "Divisibility": "./mathematics/nt/divisibility.md"